### ISSUE TITLE
Arbitrary rotation

### ISSUE THREAD

**Issue by innocenzi** [innocenzi/avatar#1]
Either via a tool in the toolbar, or via the stencil. It wasn't native to `vue-advanced-cropper` so I didn't implement it right away.

**Comment by Norserium** [comment]
Hello, @innocenzi! What do you mean by "arbitrary rotation"?

**Comment by innocenzi** [comment]
Hey, thanks for the awesome lib! It came in very handy. 😊 

I mean basically `cropper.rotate(angle)` but with the stencil. When I say that it isn't native, I meant that there's no way (at least I didn't find one) to do it with the stencil. 

What I would have liked is the ability to rotate the background image directly with the cursor. I imagined the ability to press shift and drag around the image, but instead of dragging it, it would rotate it. I guess something like the [`ResizeEvent`](https://github.com/innocenzi/avatar/blob/main/src/components/Stencil.vue#L128) would have been perfect.

**Comment by Norserium** [comment]
Thank you for answer. 

The rotation can be performed only by API now and you, unfortunately, may encounter some troubles during the creation of own wrapper that would be using it.

I'll remember your case, but I'm not sure that I'm ready to provide the solution in the foreseeable future. The best way that I see is providing to you the possibility to redefine `cropper-wrapper` (it is used to zoom and move image) and its interaction with the cropper component, but it's pretty tough task.

**Comment by innocenzi** [comment]
Thanks for this info. Honestly, that feature is not a big deal at all, You've already done a lot of good work on this library, so please don't bother looking too much into this. I think the `rotate` API will be enough to do what I want. :)
