### ISSUE TITLE
Image is sometimes not loading

### ISSUE THREAD

**Issue by innocenzi** [innocenzi/avatar#10]
Not sure what's causing this. Calling `reset` on the cropper fixes it, but I don't know how to detect an image that couldn't load. The issue appears to be quite random too.

![](https://i.imgur.com/kozA6RU.gif)

**Comment by Norserium** [comment]
@innocenzi, could you try to update `vue-advanced-cropper` to `2.3.0`? It would be very useful, if you write reproduction steps also.

**Comment by innocenzi** [comment]
Hey, sure, I updated the dependencies. It's in production right now. 

For the reproduction steps, I don't have a clear path, but it happens seemingly randomly when I load an image. For instance, you can try and go to https://avatar.innocenzi.dev/?url=https://danbooru.donmai.us/data/sample/64/7d/__original_drawn_by_toufu_inu_no_mayuge__sample-647d6b9bfcb273256b52aad9c5626280.jpg and refresh until you see the issue. 

In this GIF below, I refresh the same image until the issue happens. I also listen to the cropper component's `error` event, but it is *always* triggered no matter what.

https://i.imgur.com/xFcDZZL.gif
![](https://i.imgur.com/xFcDZZL.gif)

**Comment by innocenzi** [comment]
Note: I can't seem to reproduce that on Chrome. It is reproducible quite consistently on Firefox (dev edition) 89.0b11.

**Comment by Norserium** [comment]
Could you provide another link to an image? It is not loaded.

**Comment by Norserium** [comment]
Do you encounter this issue with locally uploaded images?

**Comment by innocenzi** [comment]
> Could you provide another link to an image? It is not loaded.

Sure, here is another link: `https://avatar.innocenzi.dev/?url=https://images.unsplash.com/photo-1565569995028-0c20b4b9d531?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=634&q=80`

Interestingly, I can't seem to reproduce the issue with this one...

> Do you encounter this issue with locally uploaded images?

Yes, it happens.

**Comment by Norserium** [comment]
Try to update to `2.3.1`. It's unlikely that I fixed it completely, but it's possible.

**Comment by innocenzi** [comment]
I can't reproduce the issue anymore. I looks like you've successfully fixed it. Thanks a lot for your time!
